version: "3"
services:
  diablo_iv_tool:
    build: ./
    image: diablo_iv_tool
    restart: always
    environment:
      - DBIVTOOL_BOT_TOKEN=${DBIVTOOL_BOT_TOKEN}
      - DBIVTOOL_DB_DRIVER=${DBIVTOOL_DB_DRIVER}
      - DBIVTOOL_DB_DSN=${DBIVTOOL_DB_DSN}

    volumes:
      - ${DBIVTOOL_VOLUME_PATH_HOST}:${DBIVTOOL_VOLUME_PATH_CONTAINER}
